# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: Camkes VM Examples

on:
  pull_request:

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        march: [nehalem, armv7a, armv8a]
    steps:
    - uses: seL4/ci-actions/camkes-vm@master
      with:
        march: ${{ matrix.march }}
    - name: Get machine queue
      uses: actions/checkout@v2
      with:
        repository: seL4/machine_queue
        path: machine_queue
        token: ${{ secrets.PRIV_REPO_TOKEN }}
    - name: Upload images
      uses: actions/upload-artifact@v2
      with:
        name: images-${{ matrix.march }}
        path: '*-images.tar.gz'
    - name: Download image
      uses: actions/download-artifact@v2
      with:
        name: images-${{ matrix.march }}
    - name: Run
      uses: seL4/ci-actions/camkes-vm-hw@master
      with:
        march: ${{ matrix.march }}
        index: $${{ strategy.job-index }}
      env:
        HW_SSH: ${{ secrets.HW_SSH }}
